# Generated by Django 5.0.2 on 2024-02-28 08:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import main.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='Umumiy miqdori')),
            ],
            options={
                'verbose_name': 'Cassa',
                'verbose_name_plural': 'Kassallar',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Bolimlar',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Ism')),
                ('number', models.CharField(max_length=200, verbose_name='Raqam')),
                ('bio', models.TextField()),
                ('extra_info', models.TextField(max_length=255, verbose_name="Qo'shimcha ma'lumot")),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Jihozlar',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Yaratilgan')),
                ('amount', models.IntegerField(verbose_name='Jami_summma')),
                ('reason', models.CharField(max_length=255, verbose_name='Sabab')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Kirimlar',
            },
        ),
        migrations.CreateModel(
            name='Info_about_clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_patients_number', models.IntegerField(verbose_name='Umumiy kasallar soni')),
                ('total_employees_number', models.IntegerField(verbose_name='Umumiy ishchilar soni')),
                ('bio', models.TextField()),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Invalid phone number', regex='^[\\+]9{2}8{1}[0-9]{9}$')], verbose_name='Telefon raqam')),
            ],
            options={
                'verbose_name': 'Info_about_clinic',
                'verbose_name_plural': 'Klinika haqida malumotlar',
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Yaratilgan')),
                ('amount', models.IntegerField(verbose_name='Jami')),
                ('reason', models.CharField(max_length=255, verbose_name='Sabab')),
            ],
            options={
                'verbose_name': 'Revenue',
                'verbose_name_plural': 'Chiqimlar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(db_index=True, max_length=112, verbose_name="To'liq ism sharif")),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Invalid phone number', regex='^[\\+]9{2}8{1}[0-9]{9}$')], verbose_name='Telefon raqam')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Foydalanuvchilar',
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'doctor'), (2, 'manager'), (3, 'admin'), (4, 'nurse'), (5, 'director'), (6, 'cooker')], verbose_name='Holat')),
                ('salary', models.PositiveIntegerField(verbose_name='Maosh')),
                ('work_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ish vaqti')),
                ('experince', models.CharField(max_length=255, verbose_name='Tajriba')),
                ('bio', models.TextField(blank=True, null=True, verbose_name="Ma' lumot")),
                ('age', models.IntegerField(default=18, verbose_name='Yosh')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department', verbose_name="Bo'lim")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Ishchilar',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=200, verbose_name="To'liq ism sharif")),
                ('age', models.IntegerField(default=18, verbose_name='Yosh')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1, verbose_name='Jins')),
                ('address', models.CharField(max_length=200, verbose_name='Manzil')),
                ('photo', models.ImageField(upload_to='patintent_phoot/', validators=[main.validators.ImageFileValidator()])),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Invalid phone number', regex='^[\\+]9{2}8{1}[0-9]{9}$')], verbose_name='Telefon raqam')),
                ('extra_phone_number', models.IntegerField(blank=True, max_length=13, null=True, verbose_name="Qo'shimcha telefon raqam")),
                ('bio', models.TextField()),
                ('stayed_day', models.DateField(verbose_name='Necha kun qolishi')),
                ('payment_status', models.IntegerField(choices=[(1, 'full_paid'), (2, 'part_paid'), (3, 'unpaid')], default=3, verbose_name="To'lov  holati")),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name='Doktor')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Bemorlar',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Kommentariya')),
                ('status', models.IntegerField(choices=[(1, 'comment'), (1, 'complain'), (1, 'suggest')], default=1)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Yaratilgan')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Kommentariyalar',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Yaratilgan ')),
                ('payment_amount', models.IntegerField(verbose_name="To'lov miqdori")),
                ('payment_type', models.IntegerField(choices=[(1, 'cash'), (2, 'by_card'), (3, 'other')], default=3, verbose_name="To'lov turi")),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Bemorlar',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name="Sig'imi")),
                ('status', models.IntegerField(choices=[(1, 'lux'), (2, 'free'), (3, 'econom'), (4, 'other')], default=4, verbose_name='Holat')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Zakaz qilndi')),
                ('other_info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha  ma'lumot")),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department', verbose_name="Bo'lim")),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.equipment', verbose_name='Jihoz')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Xonalar',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room'),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=0, verbose_name='Boshlangan vaqt')),
                ('start_time', models.DateTimeField(max_length=200, verbose_name='Tugagan vaqt')),
                ('end_time', models.CharField(max_length=200, verbose_name='Tugagan vaqt')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Yaratilgan')),
                ('employees', models.ManyToManyField(to='main.employee', verbose_name='Doktorlar')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient', verbose_name='Bemor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room', verbose_name='Xona')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operatsiyalar',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room', verbose_name='Xona'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
